### ISSUE TITLE
Default nuget schema is wrong

### ISSUE THREAD

**Issue by Sammers21** [artipie/nuget-adapter#100]
The namespace schema used by the adapter is `http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd`, which ends up in failed attempts to publish a package to a NuGet repository, that is all because the default schema defined by the official NuGet client(version 5.6.0) is `http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd`. 

I think the XML schema should be ignored since we can stick any of existed ones.

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.1`
