### ISSUE TITLE
NuGet repository SDK

### ISSUE THREAD

**Issue by g4s8** [artipie/nuget-adapter#141]
Add NuGet repository SDK with this operations (TODO: change if needed):
 - [x] ~Get package by name and version~ (out of scope)
 - [x] Add package to repository (parse package metadata SDK)
 - [x] ~Get package list by query (packageID, version: `GET /Packages(Id='{id}', Version='{version}')`)~ (out of scope)
 - [x] ~Get repository metadata (if relevant, `GET /$metadata` request)~ (out of scope)
 - [x] ~Search packages by filter query (see `GET /Search()?filter={filter}` request)~ (out of scope)

After discussions with our colleagues, we came to agreement that nuget repository SDK should provide methods to obtain package metadata from `.nupkg` file. SDK should work with `.nupkg` given as `InputStream` and provide following metadata information:
- [x] required metadata fields: package id, version, description, authors
- [x] optional fields: title, licenseUrl, requireLicenseAcceptance, tags, projectUrl, releaseNotes
- [x] dependencies list (implemented, but format may change by our colleagues request)
- [x] package types list #179 
- [x] package version info: normalized version, is version pre-release, is version only semver 2.0.0 compliant #176 

As for nuget `search` function, sdk should provide methods to format search resulting xml by provided package info #165

**Comment by g4s8** [comment]
@rultor release, tag=`0.6`

**Comment by g4s8** [comment]
@olenagerasimova done. Also, now you can release by pushing a new tag with version name and description annotation https://github.com/artipie/nuget-adapter/commit/60168276d39b791146ce735f5c3981be89ea5ae3
E.g.
```
git tag -a 0.6
git push --tags origin
```

**Comment by loic-sharma** [comment]
About these APIs:

> * [ ] Get package list by query (packageID, version: GET /Packages(Id='{id}', Version='{version}')) (to be discussed)
> * [ ] Get repository metadata (if relevant, GET /$metadata request) (to be discussed)
> * [ ] Search packages by filter query (see GET /Search()?filter={filter} request) (to be discussed)

These are legacy V2 APIs. All new NuGet features are added to the V3 API. The V2 API is missing things like package deprecation, package signing, READMEs, license expressions. Also, we've started to deprecate the V2 APIs: https://devblogs.microsoft.com/nuget/custom-v2-odata-queries-will-be-deprecated-march-9-2021/

You can find docs on NuGet's V3 APIs here: https://docs.microsoft.com/en-us/nuget/api/overview

**Comment by g4s8** [comment]
@rultor release, tag=`1.0`
