### ISSUE TITLE
HTTP support for installing package

### ISSUE THREAD

**Issue by olegmoz** [artipie/nuget-adapter#19]
Docs:

https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#download-package-content-nupkg
https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#download-package-manifest-nuspec

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#57](https://github.com/artipie/nuget-adapter/issues/57) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#57](https://github.com/artipie/nuget-adapter/issues/57) is solved here.

**Comment by 0crat** [comment]
Job `gh:artipie/nuget-adapter#19` is not assigned, can't get performer
