### ISSUE TITLE
HTTP support for adding package

### ISSUE THREAD

**Issue by olegmoz** [artipie/nuget-adapter#20]
Docs: https://docs.microsoft.com/en-us/nuget/api/package-publish-resource#push-a-package

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
