### ISSUE TITLE
Move .nupkg instead of copying on adding

### ISSUE THREAD

**Issue by olegmoz** [artipie/nuget-adapter#21]
It should be possible after adding move feature to ASTO, see https://github.com/artipie/asto/issues/51

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/nuget-adapter#21` is not assigned, can't get performer
