### ISSUE TITLE
Version.java:37-42: `compareTo` method should respect...

### ISSUE THREAD

**Issue by 0pdd** [artipie/nuget-adapter#57]
The puzzle `19-41583cf4` from #19 has to be resolved: 

https://github.com/artipie/nuget-adapter/blob/7c2a48c5b4779832e90de8aecc2cb2d03b9ca5af/src/main/java/com/artpie/nuget/Version.java#L37-L42

The puzzle was created by @olegmoz on 19-Mar-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/nuget-adapter#57` is not assigned, can't get performer
