### ISSUE TITLE
Upgrade HTTP dependency

### ISSUE THREAD

**Issue by olegmoz** [artipie/nuget-adapter#73]
Use Header class and use Headers interface from HTTP instead of own

**Comment by olegmoz** [comment]
@g4s8 could you please create release of NuGet, so it could be embedded into Artipie core?

**Comment by 0crat** [comment]
Job `gh:artipie/nuget-adapter#73` is not assigned, can't get performer

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`
