### ISSUE TITLE
`com.artpie.nuget` package name contains typo

### ISSUE THREAD

**Issue by olegmoz** [artipie/nuget-adapter#76]
All code in project is in package `com.artpie.nuget`. it should be renamed to ``com.artipie.nuget``

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olegmoz** [comment]
@g4s8 could you please release NuGet with package name fixed?

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.1`

**Comment by g4s8** [comment]
@olegmoz done: https://github.com/artipie/nuget-adapter/issues/76#issuecomment-619831276

**Comment by olegmoz** [comment]
@g4s8 cannot find `0.1.1` on maven central. Previous release is also missing, see https://repo.maven.apache.org/maven2/com/artipie/nuget-adapter/0.1/nuget-adapter-0.1.pom

It seems that something is wrong with releasing NuGet or maybe I am doing something wrong? My dependency in pom.xml is:
```
    <dependency>
      <groupId>com.artipie</groupId>
      <artifactId>nuget-adapter</artifactId>
      <version>0.1</version>
    </dependency>
```

**Comment by 0crat** [comment]
Job `gh:artipie/nuget-adapter#76` is not assigned, can't get performer

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`

**Comment by olegmoz** [comment]
@g4s8 release still has not happened, `pdd` crashes on a binary resource

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`
