### ISSUE TITLE
Poor structure of `com.artipie.nuget.http`

### ISSUE THREAD

**Issue by olegmoz** [artipie/nuget-adapter#78]
HTTP related production & test classes in `com.artipie.nuget.http` are poorly structured, some are arranged by service and some are not.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/nuget-adapter#78` is not assigned, can't get performer
