### ISSUE TITLE
NuGet repository doesn't support authorization

### ISSUE THREAD

**Issue by g4s8** [artipie/nuget-adapter#84]
NuGet repository should support authorization like other modules. It can be done using `Permissions` and `Authentication` interfaces provided by main artipie module. E.g. in files adapter: https://github.com/artipie/files-adapter/blob/master/src/main/java/com/artipie/files/FilesSlice.java#L80

If NuGet uses HTTP basic authentication, then `BasicIdentities` class may be used: https://github.com/artipie/files-adapter/blob/master/src/main/java/com/artipie/files/FilesSlice.java#L66

**Comment by 0crat** [comment]
The job [#84](https://github.com/artipie/nuget-adapter/issues/84) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e8ad0fee-bde7-440b-917d-34aabe957d9e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#90](https://github.com/artipie/nuget-adapter/issues/90) is still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/nuget-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#90](https://github.com/artipie/nuget-adapter/issues/90), [#93](https://github.com/artipie/nuget-adapter/issues/93) are still not solved.

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by olegmoz** [comment]
@yegor256 could you please touch rultor to allow release of NuGet module?

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#90](https://github.com/artipie/nuget-adapter/issues/90) is still not solved; solved: [#93](https://github.com/artipie/nuget-adapter/issues/93).
