### ISSUE TITLE
RepositoryHttpIT.java:52-55: Enable auth in tests on...

### ISSUE THREAD

**Issue by 0pdd** [artipie/nuget-adapter#93]
The puzzle `84-b0358a9e` from #84 has to be resolved: 

https://github.com/artipie/nuget-adapter/blob/35474ce0f65e2b0dfdec344f58669fd814d65196/src/test/java/com/artipie/nuget/RepositoryHttpIT.java#L52-L55

The puzzle was created by @olegmoz on 01-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/nuget-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/nuget-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
> @0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://git...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by 0pdd** [comment]
The puzzle `84-b0358a9e` has disappeared from the source code, that's why I closed this issue.
